# Generated by Django 4.2.2 on 2023-07-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flags',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sale'), ('Feature', 'Feature')], default='New', max_length=10),
        ),
    ]
