# Generated by Django 4.2.2 on 2023-07-03 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_flags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='flags',
            new_name='flag',
        ),
    ]
